### ISSUE TITLE
Retrieve properties in bulk

### ISSUE THREAD

**Issue by siredwin** [xyproto/permissions#1]
Hello,
I have been using the 'HasEmail' function for a while but it has become too slow to iterate over as the database gets bigger.
Is there a function or a way that can retrieve a property like all emails in bulk without first retrieving all usernames?
It should be a similar function to getallusers.
I am running out of options.
Thanks

**Comment by xyproto** [comment]
Hi! Thanks for raising the issue!

I'll look into the code and see if I can find a more performant way.

**Comment by siredwin** [comment]
Thanks.
In HasEmail, this function does a lot of get operations on the database. I have had instances where the cpu hits 100%.
```
for _, username := range usernames {
		userEmail, err := state.Email(username)
		if err != nil {
			return "", err
		}
		if userEmail == email {
			return username, nil
		}
	}
```

It is too late now, but the email should have been used as the username/loginname from the beginning

**Comment by xyproto** [comment]
I would be surprised if this is not solvable with the right Redis commands, though.

**Comment by siredwin** [comment]
Please explain how that might work. I have been using pstore

**Comment by xyproto** [comment]
> It is too late now, but the email should have been used as the username/loginname from the beginning

The username is a string and you can use any type of user ID you like. It could be a number formatted as a string. It could be an e-mail address. This is up to you.

**Comment by xyproto** [comment]
I have updated the `simpleredis/v2` and `permissions` packages.

By using the Redis `SCAN` command, the performance _should_ in theory now be improved.

Please test if the `HasEmail` function in the `main` branch has better performance. If the performance is still too poor, I have a few other things I can try out.

**Comment by siredwin** [comment]
I am using pstore/hstore on Postgresql. That looks promising but it does not work for me currently.

**Comment by siredwin** [comment]
Hello,
Will this `state.users.FindIDByFieldValue("email", email)` be available for `pstore`? I am waiting to test it.
